import type { MaterialOption, NodeKind } from "./types";

export const MATERIALS: MaterialOption[] = [
  // ---------------------------------------------------------------- Крыша
  {
    id: "roof-metal-tile",
    nodeKind: "roof",
    name: "Металлочерепица",
    description: "Ступенчатый профиль, полимерное покрытие, гарантия 25 лет.",
    pricePerUnit: 640,
    unit: "m2",
    colorHex: "#8A4A32",
    textureId: "tile-metal",
    tier: "free",
  },
  {
    id: "roof-shingle",
    nodeKind: "roof",
    name: "Битумная черепица",
    description: "Гибкий шинглас внахлёст, тихая под дождём.",
    pricePerUnit: 980,
    unit: "m2",
    colorHex: "#5C4A3A",
    textureId: "tile-shingle",
    tier: "free",
  },
  {
    id: "roof-ceramic-wave",
    nodeKind: "roof",
    name: "Керамическая черепица «Волна»",
    description: "Обожжённая глина, служит более 70 лет.",
    pricePerUnit: 1780,
    unit: "m2",
    colorHex: "#8A4A32",
    textureId: "tile-wave",
    tier: "pro",
  },
  {
    id: "roof-seam",
    nodeKind: "roof",
    name: "Фальцевая кровля",
    description: "Стоячий фальц, цинк-титан, для сложных геометрий.",
    pricePerUnit: 2450,
    unit: "m2",
    colorHex: "#9CA3AA",
    textureId: "seam",
    tier: "pro",
  },

  // --------------------------------------------------------------- Фасад
  {
    id: "facade-plaster",
    nodeKind: "facade",
    name: "Декоративная штукатурка",
    description: "Минеральная база, паропроницаемая.",
    pricePerUnit: 890,
    unit: "m2",
    colorHex: "#EDE6D6",
    textureId: "plaster",
    tier: "free",
  },
  {
    id: "facade-brick-facing",
    nodeKind: "facade",
    name: "Кирпич облицовочный",
    description: "Классическая ложковая кладка, морозостойкость F100.",
    pricePerUnit: 1450,
    unit: "m2",
    colorHex: "#D9C6A5",
    textureId: "brick-running",
    tier: "free",
  },
  {
    id: "facade-brick-clinker",
    nodeKind: "facade",
    name: "Кирпич клинкерный узкий",
    description: "Длинный тонкий формат, плотный спёк, почти не впитывает воду.",
    pricePerUnit: 2050,
    unit: "m2",
    colorHex: "#8C6A52",
    textureId: "brick-clinker",
    tier: "free",
  },
  {
    id: "facade-brick-aged",
    nodeKind: "facade",
    name: "Кирпич состаренный",
    description: "Неровная фактура и разнотон — вид старой кладки.",
    pricePerUnit: 2400,
    unit: "m2",
    colorHex: "#A8846B",
    textureId: "brick-aged",
    tier: "pro",
  },
  {
    id: "facade-block",
    nodeKind: "facade",
    name: "Газобетонный блок под покраску",
    description: "Крупный формат, быстрая кладка, требует отделки.",
    pricePerUnit: 720,
    unit: "m2",
    colorHex: "#C8B9A6",
    textureId: "block",
    tier: "free",
  },
  {
    id: "facade-planken",
    nodeKind: "facade",
    name: "Планкен лиственница",
    description: "Термообработанная древесина, вентилируемый фасад.",
    pricePerUnit: 2100,
    unit: "m2",
    colorHex: "#4A3626",
    textureId: "planken",
    tier: "pro",
  },
  {
    id: "facade-hpl",
    nodeKind: "facade",
    name: "HPL-панели",
    description: "Композитные панели, скрытый крепёж.",
    pricePerUnit: 3200,
    unit: "m2",
    colorHex: "#2B2B2B",
    textureId: "panel",
    tier: "pro",
  },

  // --------------------------------------------------------------- Забор
  {
    id: "fence-profnastil",
    nodeKind: "fence",
    name: "Профнастил С8",
    description: "Оцинкованный лист с полимерным покрытием.",
    pricePerUnit: 1650,
    unit: "m",
    colorHex: "#3E2A1F",
    textureId: "profnastil",
    tier: "free",
  },
  {
    id: "fence-shtaketnik",
    nodeKind: "fence",
    name: "Евроштакетник",
    description: "Двусторонняя покраска, продувается — не парусит.",
    pricePerUnit: 1900,
    unit: "m",
    colorHex: "#41454A",
    textureId: "shtaketnik",
    tier: "free",
  },
  {
    id: "fence-forged",
    nodeKind: "fence",
    name: "Кованые секции",
    description: "Индивидуальный рисунок ковки, порошковая окраска.",
    pricePerUnit: 8400,
    unit: "m",
    colorHex: "#1C1C1C",
    textureId: "forged",
    tier: "pro",
  },

  // ----------------------------------------------------------- Фундамент
  {
    id: "foundation-strip",
    nodeKind: "foundation",
    name: "Ленточный фундамент, монолит",
    description: "Заглубление ниже точки промерзания.",
    pricePerUnit: 8900,
    unit: "m2",
    colorHex: "#6B6660",
    textureId: "concrete",
    tier: "free",
  },
  {
    id: "foundation-slab",
    nodeKind: "foundation",
    name: "Плитный фундамент УШП",
    description: "Утеплённая шведская плита с тёплым полом.",
    pricePerUnit: 14200,
    unit: "m2",
    colorHex: "#7A756E",
    textureId: "concrete",
    tier: "pro",
  },

  // ----------------------------------------------------------------- Окна
  {
    id: "window-pvc",
    nodeKind: "window",
    name: "ПВХ, двухкамерный стеклопакет",
    description: "Стандартная теплоизоляция для средней полосы.",
    pricePerUnit: 19500,
    unit: "pcs",
    colorHex: "#F2EFE8",
    textureId: "glass",
    tier: "free",
  },
  {
    id: "window-alu",
    nodeKind: "window",
    name: "Алюминий, тройной стеклопакет",
    description: "Узкая рама, повышенная теплоизоляция для Урала.",
    pricePerUnit: 41000,
    unit: "pcs",
    colorHex: "#33363A",
    textureId: "glass",
    tier: "pro",
  },

  // ---------------------------------------------------------------- Дверь
  {
    id: "door-steel",
    nodeKind: "door",
    name: "Стальная входная дверь",
    description: "Утеплённое полотно, два контура уплотнения.",
    pricePerUnit: 38000,
    unit: "pcs",
    colorHex: "#2B2B2B",
    textureId: "steel-door",
    tier: "free",
  },
  {
    id: "door-oak",
    nodeKind: "door",
    name: "Дубовая входная дверь",
    description: "Массив дуба с филёнками, покрытие маслом.",
    pricePerUnit: 96000,
    unit: "pcs",
    colorHex: "#4A3626",
    textureId: "wood-door",
    tier: "pro",
  },
];

export function materialsForKind(kind: NodeKind) {
  return MATERIALS.filter((m) => m.nodeKind === kind);
}

export function materialById(id: string) {
  return MATERIALS.find((m) => m.id === id);
}
